INSERT INTO CHILDREN (
  DOCUMENT_ID, FIRST_NAME, LAST_NAME, BIRTH_DATE, GENDER, MEDICAL_NOTES, ALLERGIES
) VALUES (
  'CH001', 'Lucas', 'Ramírez', TO_DATE('2019-05-12', 'YYYY-MM-DD'), 'MASCULINO', 'Ninguna', 'Maní'
);

INSERT INTO CHILDREN (
  DOCUMENT_ID, FIRST_NAME, LAST_NAME, BIRTH_DATE, GENDER, MEDICAL_NOTES, ALLERGIES
) VALUES (
  'CH002', 'Martina', 'López', TO_DATE('2020-09-30', 'YYYY-MM-DD'), 'FEMENINO', 'Hipotiroidismo controlado', 'Lácteos'
);

INSERT INTO CHILDREN (
  DOCUMENT_ID, FIRST_NAME, LAST_NAME, BIRTH_DATE, GENDER, MEDICAL_NOTES, ALLERGIES
) VALUES (
  'CH003', 'Tomás', 'Fernández', TO_DATE('2018-12-25', 'YYYY-MM-DD'), 'MASCULINO', NULL, NULL
);

SELECT * FROM CHILDREN;


INSERT INTO TEACHERS (DOCUMENT_ID, FIRST_NAME, LAST_NAME, PHONE_NUMBER, EMAIL, ACTIVE)
VALUES ('T123456789', 'María', 'Gómez', '3101234567', 'maria.gomez@email.com', 'Y');

INSERT INTO TEACHERS (DOCUMENT_ID, FIRST_NAME, LAST_NAME, PHONE_NUMBER, EMAIL, ACTIVE)
VALUES ('T987654321', 'Juan', 'Pérez', '3129876543', 'juan.perez@email.com', 'Y');

INSERT INTO TEACHERS (DOCUMENT_ID, FIRST_NAME, LAST_NAME, PHONE_NUMBER, EMAIL, ACTIVE)
VALUES ('T112233445', 'Luisa', 'Ramírez', '3156789123', 'luisa.ramirez@email.com', 'N');

SELECT * FROM TEACHERS;



INSERT INTO COURSES (
    NAME_COURSE, MIN_AGE_MONTHS, MAX_AGE_MONTHS, MAX_CAPACITY,
    SHIFT, MAIN_TEACHER_ID, LOCATION, ACTIVE
) VALUES (
    'Jardín Explorador', 12, 24, 20,
    'Morning', 'T112233445', 'Sala A', 'Y'
);

INSERT INTO COURSES (
    NAME_COURSE, MIN_AGE_MONTHS, MAX_AGE_MONTHS, MAX_CAPACITY,
    SHIFT, MAIN_TEACHER_ID, LOCATION, ACTIVE
) VALUES (
    'Pequeños Científicos', 24, 36, 18,
    'Afternoon', 'T987654321', 'Sala B', 'Y'
);

SELECT * FROM COURSES;

INSERT INTO GUARDIANS (DOCUMENT_ID, FIRST_NAME, LAST_NAME, RELATIONSHIP, PHONE_NUMBER, EMAIL)
VALUES ('G001', 'Laura', 'Martínez', 'Madre', '3101234567', 'laura.martinez@example.com');

INSERT INTO GUARDIANS (DOCUMENT_ID, FIRST_NAME, LAST_NAME, RELATIONSHIP, PHONE_NUMBER, EMAIL)
VALUES ('G002', 'Carlos', 'Ramírez', 'Padre', '3009876543', 'carlos.ramirez@example.com');

INSERT INTO GUARDIANS (DOCUMENT_ID, FIRST_NAME, LAST_NAME, RELATIONSHIP, PHONE_NUMBER, EMAIL)
VALUES ('G003', 'Ana', 'Gómez', 'Tía', '3125558899', 'ana.gomez@example.com');

SELECT * FROM GUARDIANS;

INSERT INTO ENROLLMENTS (CHILD_ID, GUARDIAN_ID, COURSE_ID, ENROLL_DATE, STATUS_ENROLLMENT)
VALUES ('CH002', 'G002', 3, TO_DATE('2024-09-01', 'YYYY-MM-DD'), 'PE');
SELECT * FROM ENROLLMENTS;


INSERT INTO DOCUMENTS (ENROLLMENT_ID, FILE_NAME, FILE_URI, FILE_TYPE, UPLOAD_DATE)
VALUES (1, 'dni_niño_C001.pdf', '/docs/enrollments/1/dni_niño_C001.pdf', 'dni_child', SYSDATE);